apiVersion: apps.dominodatalab.com/v1alpha1
kind: Mutation
metadata:
  name: insert-mlflow-large-artifacts-efs-based
  namespace: domino-platform
rules:
- insertVolumeMounts:
    containerSelector:
    - run
    volumeMounts:
    - mountPath: /artifacts/mlflow/{{ object['metadata']['labels']['dominodatalab.com/project-id']
        }}
      name: domino-shared-store-domino-compute-vol
      subPath: '{{ object[''metadata''][''labels''][''dominodatalab.com/project-id'']
        }}'
  jqSelector:
    query: |
      include "domsed/selectors/common";
      $__kind__ == "Pod" and
      (.metadata.labels."dominodatalab.com/workload-type" | isIn(["Workspace","Batch","Scheduled"]))
  matchBuilds: false
- insertVolumes:
  - name: prediction-data-volume
    persistentVolumeClaim:
      claimName: domino-shared-store-domino-compute
  insertVolumeMounts:
    containerSelector:
    - model
    volumeMounts:
    - mountPath: /artifacts/mlflow/{{ object['metadata']['labels']['dominodatalab.com/project-id']
        }}
      name: prediction-data-volume
      readOnly: true
      subPath: '{{ object[''metadata''][''labels''][''dominodatalab.com/project-id'']
        }}' 
  jqSelector:
    query: |
      include "domsed/selectors/common";
      $__kind__ == "Pod" and
      (.metadata.labels."dominodatalab.com/workload-type" | isIn(["ModelAPI"]))
